{% set version = '0.17.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-coursekata
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/coursekata_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/coursekata/coursekata_{{ version }}.tar.gz
  sha256: 7090b497110a730ca44023dc23e649a963574187c734bb61cfe757bc3ef9103c

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-metrics
    - r-cli >=3.2.0
    - r-dslabs >=0.7.4
    - r-ggformula >=0.10.1
    - r-ggplot2 >=3.5.0
    - r-glue >=1.6.2
    - r-lsr >=0.5.2
    - r-mosaic >=1.8.3
    - r-pak
    - r-palmerpenguins
    - r-purrr >=0.3.4
    - r-rlang >=1.0.2
    - r-supernova >=2.5.1
    - r-vctrs >=0.4.1
    - r-viridislite
  run:
    - r-base
    - r-metrics
    - r-cli >=3.2.0
    - r-dslabs >=0.7.4
    - r-ggformula >=0.10.1
    - r-ggplot2 >=3.5.0
    - r-glue >=1.6.2
    - r-lsr >=0.5.2
    - r-mosaic >=1.8.3
    - r-pak
    - r-palmerpenguins
    - r-purrr >=0.3.4
    - r-rlang >=1.0.2
    - r-supernova >=2.5.1
    - r-vctrs >=0.4.1
    - r-viridislite

test:
  commands:
    - $R -e "library('coursekata')"           # [not win]
    - "\"%R%\" -e \"library('coursekata')\""  # [win]

about:
  home: https://github.com/coursekata/coursekata-r
  license: AGPL-3.0-or-later
  summary: Easily install and load all packages and functions used in 'CourseKata' courses. Aid
    teaching with helper functions and augment generic functions to provide cohesion
    between the network of packages. Learn more about 'CourseKata' at <https://coursekata.org>.
  license_family: AGPL
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/AGPL-3'
extra:
  recipe-maintainers:
    - conda-forge/r
    - adamblake

# Package: coursekata
# Title: Packages and Functions for 'CourseKata' Courses
# Version: 0.17.0
# Date: 2024-05-24
# Authors@R: c( person("Adam", "Blake", , "adam@coursekata.org", role = c("cre", "aut"), comment = c(ORCID = "0000-0001-7881-8652")), person("Ji", "Son", , "ji@coursekata.org", role = "aut", comment = c(ORCID = "0000-0002-4258-4791")), person("Jim", "Stigler", , "jim@coursekata.org", role = "aut", comment = c(ORCID = "0000-0001-6107-7827")) )
# Description: Easily install and load all packages and functions used in 'CourseKata' courses. Aid teaching with helper functions and augment generic functions to provide cohesion between the network of packages. Learn more about 'CourseKata' at <https://coursekata.org>.
# License: AGPL (>= 3)
# URL: https://github.com/coursekata/coursekata-r
# BugReports: https://github.com/coursekata/coursekata-r/issues
# Depends: R (>= 3.6)
# Imports: cli (>= 3.2.0), dslabs (>= 0.7.4), ggformula (>= 0.10.1), ggplot2 (>= 3.5.0), glue (>= 1.6.2), lsr (>= 0.5.2), Metrics, mosaic (>= 1.8.3), pak, palmerpenguins, purrr (>= 0.3.4), rlang (>= 1.0.2), supernova (>= 2.5.1), vctrs (>= 0.4.1), viridisLite
# Suggests: fivethirtyeight (>= 0.6.2), lubridate (>= 1.8.0), mockery (>= 0.4.3), mockr (>= 0.1), readr (>= 2.1.2), readxl (>= 1.4.0), usethis (>= 2.1.6), simstudy (>= 0.5.0), testthat (>= 3.1.2), tibble(>= 3.1.7), tidyr (>= 1.2.0), vdiffr (>= 1.0.2), withr (>= 2.5.0)
# Config/testthat/edition: 3
# Language: en-US
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 7.3.1
# NeedsCompilation: no
# Packaged: 2024-05-24 20:27:20 UTC; adamblake
# Author: Adam Blake [cre, aut] (<https://orcid.org/0000-0001-7881-8652>), Ji Son [aut] (<https://orcid.org/0000-0002-4258-4791>), Jim Stigler [aut] (<https://orcid.org/0000-0001-6107-7827>)
# Maintainer: Adam Blake <adam@coursekata.org>
# Repository: CRAN
# Date/Publication: 2024-05-26 16:50:02 UTC
